# Objective
Dive deep into working with datasets using _pandas_.

# Things To Learn
* Creating and working with _pandas dataframes_ and _series_.
* Loading and getting an overview of data.
* Manipulating datasets.
* Selecting, grouping and sorting data.

# Submission Guidelines
* Your finished _Jupyter Notebook_ - both as `.ipynb` and exported `.pdf`.

# Task: Manually Creating A _Dataframe_ (Fabian Oppermann)

**Task:**
Import _pandas_ and manually create a _dataframe_ containing data about a domain **you're passionate about**. Your dataframe should...

* ...contain at least 4 rows.
* ...contain at least 3 column, of which at least one should be numeric and one should be suitable as a _key_ (i.e. _index_).

Next, manually create a _series_ and add it as additional column to your dataset.

Finally, set the index of your dataframe to a suitable column.

In [13]:
import pandas as pd

In [14]:
# https://pandas.pydata.org/docs/reference/api/pandas.Series.html
data = {
    'Species': ['Acerifolia', 'Platanus', 'Pinus pinea', 'Quercus'],
    'Health': ['Good', 'Fair', 'Good', 'Good'],
    'Health_Number': [10, 20, 15, 40]
}

species_df = pd.DataFrame(data)

# Manually creating a series and adding it as an additional column
conservation_status = pd.Series(['Vulnerable', 'Endangered', 'Vulnerable', 'Vulnerable'], name='Conservation_Status')
species_df['Conservation_Status'] = conservation_status

# Setting the index of the dataframe to 'Species'
species_df.set_index('Species', inplace=True)

print(species_df)

            Health  Health_Number Conservation_Status
Species
Acerifolia    Good             10          Vulnerable
Platanus      Fair             20          Endangered
Pinus pinea   Good             15          Vulnerable
Quercus       Good             40          Vulnerable

# Task: Importing And Getting An Overview (Fabian Oppermann)

Read the _ramen_ ratings from the provided file and get an overview of the data:

* Take a look at some rows from the top, bottom or random positions...
* Use summary functions to get a statistical overview of the data.
* Find out what data types we're dealing with.
* Identify what column would be suitable as index and set it!

In [15]:
ramen_df = pd.read_csv('./ramen-ratings.csv')

# https://pandas.pydata.org/docs/reference/frame.html
print(ramen_df.head()) # Top
print('-' * 50)
print(ramen_df.tail()) # Bottom
print('-' * 50)
print(ramen_df.sample(5)) # Random
print('-' * 50)
print(ramen_df.describe()) # Summary
print('-' * 50)
print(ramen_df.info()) # Info

   Review #           Brand  \
0      2580       New Touch
1      2579        Just Way
2      2578          Nissin
3      2577         Wei Lih
4      2576  Ching's Secret

                                             Variety Style Country Stars  \
0                          T's Restaurant Tantanmen    Cup   Japan  3.75
1  Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...  Pack  Taiwan     1
2                      Cup Noodles Chicken Vegetable   Cup     USA  2.25
3                      GGE Ramen Snack Tomato Flavor  Pack  Taiwan  2.75
4                                    Singapore Curry  Pack   India  3.75

  Top Ten
0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
--------------------------------------------------
      Review #     Brand                                            Variety  \
2575         5     Vifon  Hu Tiu Nam Vang ["Phnom Penh" style] Asian Sty...
2576         4   Wai Wai                     Oriental Style Instant Noodles
2577         3   Wai Wai                                     Tom Yum Shrimp
2578         2   Wai Wai                               Tom Yum Chili Flavor
2579         1  Westbrae                                         Miso Ramen

     Style   Country Stars Top Ten
2575  Bowl   Vietnam   3.5     NaN
2576  Pack  Thailand     1     NaN
2577  Pack  Thailand     2     NaN
2578  Pack  Thailand     2     NaN
2579  Pack       USA   0.5     NaN
--------------------------------------------------
      Review #       Brand                                            Variety  \
693       1887       Myojo                                        Mee Poh Dry
2478       102     Indomie                                           Soto Mie
1943       637  Snapdragon                       Chinese Mushroom Rice Noodle
1584       996    Maruchan                                Bowl Chicken Flavor
1457      1123    Maruchan  Fresh Yaki-Soba Stir Fry Noodles With Seasonin...

     Style    Country Stars Top Ten
693   Pack  Singapore  4.25     NaN
2478  Pack  Indonesia   1.5     NaN
1943   Cup  Singapore   2.5     NaN
1584  Bowl        USA     4     NaN
1457  Pack      Japan  4.25     NaN
--------------------------------------------------
          Review #
count  2580.000000
mean   1290.500000
std     744.926171
min       1.000000
25%     645.750000
50%    1290.500000
75%    1935.250000
max    2580.000000
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2580 entries, 0 to 2579
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Review #  2580 non-null   int64
 1   Brand     2580 non-null   object
 2   Variety   2580 non-null   object
 3   Style     2578 non-null   object
 4   Country   2580 non-null   object
 5   Stars     2580 non-null   object
 6   Top Ten   41 non-null     object
dtypes: int64(1), object(6)
memory usage: 141.2+ KB
None

# Task: Dealing With Erroneous Rows

As you surely noticed, the star ratings are not included in the numerical statistics. Find out why and fix this, so we can work with the column:

* Take a look at the column's data type (should have been determined in the last task). Try casting it to `float`!
* Find out all the unique values in the column.
* Now that you know the faulty values, identify their rows and drop them. This should affect 3 rows.
* Try casting the the column again and make sure we can now calculate statistics on it by printing the mean of it.

In [16]:
# Converting 'Points' into int
pd.to_numeric(ramen_df['Stars'], errors='coerce')

# Unique values
print(ramen_df['Stars'].unique())

['3.75' '1' '2.25' '2.75' '4.75' '4' '0.25' '2.5' '5' '4.25' '4.5' '3.5'
 'Unrated' '1.5' '3.25' '2' '0' '3' '0.5' '4.00' '5.0' '3.50' '3.8' '4.3'
 '2.3' '5.00' '3.3' '4.0' '3.00' '1.75' '3.0' '4.50' '0.75' '1.25' '1.1'
 '2.1' '0.9' '3.1' '4.125' '3.125' '2.125' '2.9' '0.1' '2.8' '3.7' '3.4'
 '3.6' '2.85' '3.2' '3.65' '1.8']

# Task: Missing Values (Fabian Oppermann)

We don't want to deal with missing values in this example. Do the following:

* Find out how many values are missing in each column.
* One column should be missing 2 values. Identify the relevant rows and delete them.
* One column should be missing a lot of values. Delete the whole column.

In [17]:
# Missing values
print(ramen_df.isnull().sum())

#?

Review #       0
Brand          0
Variety        0
Style          2
Country        0
Stars          0
Top Ten     2539
dtype: int64

# Task: Create A Price-Column (Fabian Oppermann)

Unfortunately the ramen reviews don't contain a price column. Let's _fake_ one with rough estimates:

* A _pack_ of ramen should cost 0.79.
* A _bowl_ of ramen should cost 1.79.
* A _cup_ of ramen should cost 1.29.
* A _tray_ of ramen should cost 2.19.
* All other types should cost 1.09.

Create a function calculating the price based on the style. Use `map` to create a series and add it as a new column to your dataframe.

In [18]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html#pandas.DataFrame.map

COST_PACK = 0.79
COST_BOWL = 1.79
COST_CUP = 0.99
COST_TRAY = 2.19
COST_OTHER = 1.09


def calculate_price(style):
    if style == 'Pack':
        return 0.79
    elif style == 'Bowl':
        return 1.79
    elif style == 'Cup':
        return 1.29
    elif style == 'Tray':
        return 2.19
    else:
        return 1.09


ramen_df['Price'] = ramen_df['Style'].map(calculate_price)

print(ramen_df.head())

   Review #           Brand  \
0      2580       New Touch
1      2579        Just Way
2      2578          Nissin
3      2577         Wei Lih
4      2576  Ching's Secret

                                             Variety Style Country Stars  \
0                          T's Restaurant Tantanmen    Cup   Japan  3.75
1  Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...  Pack  Taiwan     1
2                      Cup Noodles Chicken Vegetable   Cup     USA  2.25
3                      GGE Ramen Snack Tomato Flavor  Pack  Taiwan  2.75
4                                    Singapore Curry  Pack   India  3.75

  Top Ten  Price
0     NaN   1.29
1     NaN   0.79
2     NaN   1.29
3     NaN   0.79
4     NaN   0.79

# Task: From Stars To Points (Fabian Oppermann)

Let's switch from a _star rating_ to a _point rating_ between 1 and 100.

* Calculate the points based on the stars, where 5 stars equal 100 points.
* Change the column name from _Stars_ to _Points_.

In [19]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename

ramen_df = ramen_df.rename(columns={'Stars': 'Points'})
ramen_df['Points'] = ramen_df['Points'].apply(lambda x: float(x) if x != 'Unrated' else None) * 10

# Task: Create A Recommendation-Column (Fabian Oppermann)

Let's create a new column containing a textual recommendation:

* Ramen with points higher or equal than 90 points get either _Amazing value!_ (for prices benath 1.3) or _Expensive but delicious!_.
* Other ramen with ratings above 80 should read _Must-Try!_.
* Other cheap ramen with a price below 1 should read _Budget choice!_.
* All other ramen should read _Why not?_.

Since you need multiple columns to calculate the recommendation, you need to use `apply`. Check how often each recommendation text appears afterwards!

In [20]:
ramen_df['Textual_Recom'] = ramen_df.apply(
    lambda row: 'Amazing value!' if float(row['Points']) >= 90 and float(row['Price']) < 1.3 else
                'Expensive but delicious!' if float(row['Points']) >= 90 else
                'Must-Try!' if float(row['Points']) > 80 else
                'Budget choice!' if float(row['Price']) < 1 else
                'Why not?', axis=1)

print(ramen_df['Textual_Recom'].value_counts())

Textual_Recom
Budget choice!    1531
Why not?          1049
Name: count, dtype: int64

# Task: Export Data

At this point it makes sense to backup our processed dataframe. Export the data into a file `ramen_processed.csv` into a subfolder `output` and compare your results to the provided solution.

In [21]:
import os

# Create the output directory if it does not exist
os.makedirs('output', exist_ok=True)

ramen_df.to_csv('output/ramen_processed.csv', index=False)

# Task: Selecting Data (_Integer-Based_) (Fabian Oppermann)

You can now either use the dataset you've worked on so far or - if in doubt - load our `ramen_processed_solution.csv` for the next tasks.

Solve the following tasks to sharpen your selecting skills:

* Get the first two columns of the last ten rows.
* Get the 4<sup>th</sup> column of the 15<sup>th</sup> row.
* Get the second and the last column of the second last ten rows.
* Get everything but the first column of the 20<sup>th</sup>, 30<sup>th</sup>, 40<sup>th</sup> and 50</sup>th</sup> row.
* Get every column of the 100<sup>th</sup> up to (and including) the 200<sup>th</sup> row.
* Get the third column of every row.

In [22]:
# Get the first two columns of the last ten rows
print(ramen_df.iloc[-10:, :2])
print('-' * 50)

# Get the 4th column of the 15th row
print(ramen_df.iloc[14, 3])
print('-' * 50)

# Get the second and the last column of the second last ten rows
print(ramen_df.iloc[-20:-10, [1, -1]])
print('-' * 50)

# Get everything but the first column of the 20th, 30th, 40th and 50th row
print(ramen_df.iloc[[19, 29, 39, 49], 1:])
print('-' * 50)

# Get every column of the 100th up to (and including) the 200th row
print(ramen_df.iloc[99:200, :])
print('-' * 50)

# Get the third column of every row
print(ramen_df.iloc[:, 2])
print('-' * 50)

      Review #     Brand
2570        10     Smack
2571         9     Sutah
2572         8    Tung-I
2573         7   Ve Wong
2574         6     Vifon
2575         5     Vifon
2576         4   Wai Wai
2577         3   Wai Wai
2578         2   Wai Wai
2579         1  Westbrae
--------------------------------------------------
Pack
--------------------------------------------------
                Brand   Textual_Recom
2560         Nongshim  Budget choice!
2561         Nongshim  Budget choice!
2562           Ottogi  Budget choice!
2563        Quickchow  Budget choice!
2564          Samyang  Budget choice!
2565          Samyang  Budget choice!
2566          Samyang  Budget choice!
2567  Sapporo Ichiban  Budget choice!
2568  Sapporo Ichiban  Budget choice!
2569      Six Fortune  Budget choice!
--------------------------------------------------
            Brand                                            Variety Style  \
19          Paldo                                    Premium Gomtang  Pack
29           KOKA           Signature Tom Yum Flavor Instant Noodles  Pack
39         Nissin  Cup Noodles Very Veggie Spicy Chicken Flavor R...   Cup
49  Uni-President                               Pickled Cabbage Beef  Pack

        Country  Points Top Ten  Price   Textual_Recom
19  South Korea    40.0     NaN   0.79  Budget choice!
29    Singapore    40.0     NaN   0.79  Budget choice!
39          USA    50.0     NaN   1.29        Why not?
49        China    42.5     NaN   0.79  Budget choice!
--------------------------------------------------
     Review #             Brand  \
99       2481     Samyang Foods
100      2480           Acecook
101      2479             E-Zee
102      2478       Kiki Noodle
103      2477       Kiki Noodle
..        ...               ...
195      2385     Uni-President
196      2384  Sichuan Guangyou
197      2383            Nissin
198      2382          Nongshim
199      2381            Nissin

                                               Variety Style      Country  \
99                                  Buldak Bokkeummyun   Cup  South Korea
100                                    Pork Wantan Men  Bowl        Japan
101                    Instant Noodles Chicken Flavour  Pack     Malaysia
102                    Scallion Oil & Soy Sauce Noodle  Pack       Taiwan
103                       Sichuan Spices Flavor Noodle  Pack       Taiwan
..                                                 ...   ...          ...
195   Man Han Feast Chilli Beef Flavor Instant Noodles  Bowl       Taiwan
196  9999 Chongqing Artificial Beef Flavor Instant ...  Pack        China
197  Cup Noodles Beef Flavor Ramen Noodle Soup (New...   Cup          USA
198                             Seaweed Instant Noodle   Cup  South Korea
199         Demae Iccho Seafood Flavour Instant Noodle   Cup    Hong Kong

     Points Top Ten  Price   Textual_Recom
99     37.5     NaN   1.29        Why not?
100    42.5     NaN   1.79        Why not?
101    40.0     NaN   0.79  Budget choice!
102    50.0     NaN   0.79  Budget choice!
103    50.0     NaN   0.79  Budget choice!
..      ...     ...    ...             ...
195    47.5     NaN   1.79        Why not?
196    42.5     NaN   0.79  Budget choice!
197    35.0     NaN   1.29        Why not?
198     5.0     NaN   1.29        Why not?
199    47.5     NaN   1.29        Why not?

[101 rows x 9 columns]
--------------------------------------------------
0                               T's Restaurant Tantanmen
1       Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...
2                           Cup Noodles Chicken Vegetable
3                           GGE Ramen Snack Tomato Flavor
4                                         Singapore Curry
                              ...
2575    Hu Tiu Nam Vang ["Phnom Penh" style] Asian Sty...
2576                       Oriental Style Instant Noodles
2577                                       Tom Yum Shrimp
2578                                 Tom Yum Chili Flavor
2579                                           Miso Ramen
Name: Variety, Length: 2580, dtype: object
--------------------------------------------------

# Task: Selecting Data (_Label-Based_) (Fabian Oppermann)

Solve the following tasks to sharpen your selecting skills:

* Get the variety and textual recommendation for the review _#1235_.
* Get all columns but the textual recommendation for the reviews from (and including) _#5_ to (and including) _#10_.
* Get the style and points for the reviews _#123_, _#234_ and _#345_.
* Get the variety, style and country for all reviews.

In [23]:
# Get the variety and textual recommendation for the review #1235
print(ramen_df.loc[ramen_df['Review #'] == 1235, ['Variety', 'Textual_Recom']])
print('-' * 50)

# Get all columns but the textual recommendation for the reviews from #5 to #10
print(ramen_df.loc[(ramen_df['Review #'] >= 5) & (ramen_df['Review #'] <= 10)].drop(columns=['Textual_Recom']))
print('-' * 50)

# Get the style and points for the reviews #123, #234 and #345
print(ramen_df.loc[ramen_df['Review #'].isin([123, 234, 345]), ['Style', 'Points']])
print('-' * 50)

# Get the variety, style and country for all reviews
print(ramen_df[['Variety', 'Style', 'Country']])
print('-' * 50)

                                                Variety   Textual_Recom
1345  Demae Ramen Miso Tonkotsu Artificial Pork Flav...  Budget choice!
--------------------------------------------------
      Review #    Brand                                            Variety  \
2570        10    Smack                                     Vegetable Beef
2571         9    Sutah                                         Cup Noodle
2572         8   Tung-I                   Chinese Beef Instant Rice Noodle
2573         7  Ve Wong                                      Mushroom Pork
2574         6    Vifon                                           Nam Vang
2575         5    Vifon  Hu Tiu Nam Vang ["Phnom Penh" style] Asian Sty...

     Style      Country  Points Top Ten  Price
2570  Pack          USA    15.0     NaN   0.79
2571   Cup  South Korea    20.0     NaN   1.29
2572  Pack       Taiwan    30.0     NaN   0.79
2573  Pack      Vietnam    10.0     NaN   0.79
2574  Pack      Vietnam    25.0     NaN   0.79
2575  Bowl      Vietnam    35.0     NaN   1.79
--------------------------------------------------
     Style  Points
2235  Pack    35.0
2346  Pack    37.5
2457  Pack    37.0
--------------------------------------------------
                                                Variety Style   Country
0                             T's Restaurant Tantanmen    Cup     Japan
1     Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...  Pack    Taiwan
2                         Cup Noodles Chicken Vegetable   Cup       USA
3                         GGE Ramen Snack Tomato Flavor  Pack    Taiwan
4                                       Singapore Curry  Pack     India
...                                                 ...   ...       ...
2575  Hu Tiu Nam Vang ["Phnom Penh" style] Asian Sty...  Bowl   Vietnam
2576                     Oriental Style Instant Noodles  Pack  Thailand
2577                                     Tom Yum Shrimp  Pack  Thailand
2578                               Tom Yum Chili Flavor  Pack  Thailand
2579                                         Miso Ramen  Pack       USA

[2580 rows x 3 columns]
--------------------------------------------------

# Task: Conditional Selection (Fabian Oppermann)

Solve the following tasks to sharpen your selection skills:

* Get everything about ramen that comes in a bowl.
* Get variety, style and points of all ramen that comes from Germany.
* Get the columns from brand up to country of all ramen that comes in a cup and has a rating lower than 10 points.
* Get brand, variety and points of all ramen either produced by _Samyang_ or having a rating over 95 points.
* Get everything but price and recommendation for all ramen containing _Hello Kitty_ in their variety field.
* Get everything up to country for all ramen from the brands _Knorr_, _Vifon_ and _Yum Yum_.

In [24]:
# Get everything about ramen that comes in a bowl
print(ramen_df[ramen_df['Style'] == 'Bowl'])
print('-' * 50)

# Get variety, style and points of all ramen that comes from Germany
print(ramen_df[ramen_df['Country'] == 'Germany'][['Variety', 'Style', 'Points']])
print('-' * 50)

# Get the columns from brand up to country of all ramen that comes in a cup and has a rating lower than 10 points
print(ramen_df[(ramen_df['Style'] == 'Cup') & (ramen_df['Points'] < 10)].loc[:, 'Brand':'Country'])
print('-' * 50)

# Get brand, variety and points of all ramen either produced by Samyang or having a rating over 95 points
print(ramen_df[(ramen_df['Brand'] == 'Samyang') | (ramen_df['Points'] > 95)][['Brand', 'Variety', 'Points']])
print('-' * 50)

# Get everything but price and recommendation for all ramen containing Hello Kitty in their variety field
print(ramen_df[ramen_df['Variety'].str.contains('Hello Kitty')].drop(columns=['Price', 'Textual_Recom']))
print('-' * 50)

# Get everything up to country for all ramen from the brands Knorr, Vifon and Yum Yum
print(ramen_df[ramen_df['Brand'].isin(['Knorr', 'Vifon', 'Yum Yum'])].loc[:, :'Country'])
print('-' * 50)

      Review #             Brand  \
13        2567            Nissin
25        2555     Samyang Foods
27        2553            Nissin
28        2552           MyKuali
33        2547  Sichuan Guangyou
...        ...               ...
2537        43       Kim Ve Wong
2539        41       Little Cook
2541        39         Lucky Me!
2551        29          Mee Jang
2575         5             Vifon

                                                Variety Style      Country  \
13                         Deka Buto Kimchi Pork Flavor  Bowl        Japan
25                            Song Song Kimchi Big Bowl  Bowl  South Korea
27                   Hakata Ramen Noodle White Tonkotsu  Bowl        Japan
28              Penang White Curry Rice Vermicelli Soup  Bowl     Malaysia
33                          Chongqing Spicy Hot Noodles  Bowl        China
...                                                 ...   ...          ...
2537          Jaopai Series: Vegetarian Instant Noodles  Bowl       Taiwan
2539                                  Pork Mustard Stem  Bowl     Thailand
2541                              Supreme Bulalo Flavor  Bowl  Philippines
2551                                     Tom Yum Shrimp  Bowl     Thailand
2575  Hu Tiu Nam Vang ["Phnom Penh" style] Asian Sty...  Bowl      Vietnam

      Points Top Ten  Price Textual_Recom
13      45.0     NaN   1.79      Why not?
25      42.5     NaN   1.79      Why not?
27      47.5     NaN   1.79      Why not?
28      50.0     NaN   1.79      Why not?
33      40.0     NaN   1.79      Why not?
...      ...     ...    ...           ...
2537     0.0     NaN   1.79      Why not?
2539     5.0     NaN   1.79      Why not?
2541    30.0     NaN   1.79      Why not?
2551    35.0     NaN   1.79      Why not?
2575    35.0     NaN   1.79      Why not?

[481 rows x 9 columns]
--------------------------------------------------
                                                Variety Style  Points
82                               Demae Ramen Spicy Beef  Pack    37.5
83                                    Cup Noodles Spicy   Cup    37.5
84                                            Soba Thai  Pack    45.0
85                           Cup Noodles Huhn (Chicken)   Cup    37.5
86                            Demae Ramen Korean Kimchi  Pack    35.0
87                                    Cup Noodles Curry   Cup    37.5
89                                Soba Yakitori Chicken   Cup    50.0
90                           Demae Ramen Garlic Chicken  Pack    35.0
91                              Cup Noodles Ente (Duck)   Cup    30.0
92                             Demae Ramen Thai Tom Yum  Pack    37.5
93                                   Soba Sukiyaki Beef   Cup    45.0
94                                    Demae Ramen Spicy  Pack    35.0
95                                  Cup Noodles Shrimps   Cup    30.0
96                          Demae Ramen Tokyo Soy Sauce  Pack    40.0
605                          Soba Fried Noodles Classic  Pack    32.5
664                         Soba Fried Noodles Teriyaki  Pack    30.0
711                            Soba Fried Noodles Chili  Pack    35.0
767                            Soba Fried Noodles Curry  Pack    42.5
847                        Instant Noodles Beef Flavour  Pack    37.5
943                   Instant Nudelsuppe Huhn Geschmack  Pack    30.0
1090    Soba Chili Noodles With Japanese Yakisoba Sauce   Cup    35.0
1104                  Instant Nudelsuppe Shrimp Flavour  Pack    35.0
1111        Oriental Style Instant Noodles Beef Flavour  Pack    32.5
1115                Shrimp "Tom Yum" Instant Nudelsuppe  Pack    35.0
1212  Soba Teriyaki Noodles With Japanese Yakisoba S...   Cup    30.0
1358  Soba Classic Noodles With Japanese Yakisoba Sauce   Cup    37.5
1387    Soba Curry Noodles With Japanese Yakisoba Sauce   Cup    37.5
--------------------------------------------------
                Brand                                            Variety  \
154   Dr. McDougall's                         Vegan Pad Thai Noodle Soup
198          Nongshim                             Seaweed Instant Noodle
557      Urban Noodle                   Authentic Street Food Black Bean
624          Maruchan                           Spicy Tomato Salsa Ramen
657           Conimex                          Oriental Noodles Teriyaki
719           Conimex                      Oriental Noodles Groene Curry
780    Crystal Noodle                        Soup All Natural Hot & Sour
938        Campbell's                Hearty Noodles Savoury Beef Flavour
952             Azami                                Kimchee Noodle Soup
1177            Tesco          Everyday Value Chicken & Mushroom Flavour
1209       Campbell's                        Hearty Noodles Thai Flavour
1996           Baijia  Single Noble Black Bone Chicken Sweet Potato T...
2125           Baijia                 Single Noble Pickled Radish & Duck

     Style      Country
154    Cup          USA
198    Cup  South Korea
557    Cup           UK
624    Cup        Japan
657    Cup  Netherlands
719    Cup  Netherlands
780    Cup          USA
938    Cup       Canada
952    Cup       Canada
1177   Cup           UK
1209   Cup       Canada
1996   Cup        China
2125   Cup        China
--------------------------------------------------
        Brand                          Variety  Points
1888  Samyang         Assorted Vegetable Ramen    37.5
1905  Samyang                Nagasaki Jjampong    47.5
2027  Samyang                   60 Ingredients    27.5
2058  Samyang                         Hot Beef    42.5
2072  Samyang                             Beef    37.5
2119  Samyang             Sutah Hot Spicy Beef    35.0
2142  Samyang                             Beef    37.5
2278  Samyang         Bowl Noodle Picante Beef    37.5
2363  Samyang               Bowl Noodle Kimchi    40.0
2381  Samyang            Chinese Soybean Paste    20.0
2405  Samyang  Cold Ramen With Ponytail Radish    30.0
2409  Samyang     Japanese Seafood Flavor Udon    37.5
2411  Samyang                    Seafood Party    22.5
2460  Samyang                             Beef    40.0
2466  Samyang                           Kimchi    29.0
2496  Samyang          Kalgug-Su Assorted Clam    18.0
2564  Samyang                Kalgug-Su (Spicy)    35.0
2565  Samyang               Pojangmacha U-dong    25.0
2566  Samyang                              Hot    35.0
--------------------------------------------------
      Review #             Brand  \
536       2044              Doll
1211      1369  A-Sha Dry Noodle
1252      1328  A-Sha Dry Noodle
1363      1217              Doll
1390      1190            Sanrio

                                                Variety Style    Country  \
536   Hello Kitty Dim Sum Noodle Japanese Soy Sauce ...   Cup  Hong Kong
1211               Hello Kitty Za Jiang (Soybean Sauce)  Pack     Taiwan
1252                  Hello Kitty La Wei (Spicy Flavor)  Pack     Taiwan
1363  Hello Kitty Dim Sum Noodle Japanese Curry Flavour   Cup  Hong Kong
1390             Hello Kitty Hakata Shoyutonkotsu Ramen  Bowl      Japan

      Points Top Ten
536     30.0     NaN
1211    32.5     NaN
1252    37.5     NaN
1363    35.0     NaN
1390    37.5     NaN
--------------------------------------------------
      Review #    Brand                                            Variety  \
226       2354    Vifon  Viet Cuisine Bun Rieu Cua Sour Crab Soup Insta...
234       2346    Knorr                        Chatt Patta Instant Noodles
387       2193    Knorr                   Chicken Flavored Instant Noodles
674       1906    Vifon        Chicken Flavour Asian Style Instant Noodles
713       1867  Yum Yum   Premier Bowl Instant Noodles Stewed Pork Flavour
748       1832  Yum Yum  Instant Flat Shaped Noodles Boat Noodles Nam T...
761       1819  Yum Yum          Premier Bowl Instant Noodles Suki Flavour
764       1816    Vifon  Asian Style Instant Noodles Artificial Beef Fl...
831       1749  Yum Yum  Jumbo Instant Noodles Tom Yum Kung Creamy Flavour
865       1715  Yum Yum                 Instant Noodles Minced Pork Flavor
914       1666    Vifon                  Curry Instant Noodle With Chicken
1058      1522    Vifon                   Instant Porridge Seafood Flavour
1060      1520  Yum Yum      Oriental Style Instant Noodles Wasabi Flavour
1070      1510    Knorr                  Quick Serve Macaroni Wonton Broth
1143      1437    Knorr     Quick Serve Macaroni Abalone & Chicken Flavour
1161      1419    Vifon               Ngon-Ngon Tom Yum Minced Pork Noodle
1251      1329    Vifon  Oriental Style Instant Noodle Mi Ga Chicken Fl...
1271      1309  Yum Yum     Oriental Style Instant Noodles Seafood Flavour
1279      1301    Knorr                  Quick Serve Macaroni Shrimp Broth
1303      1277    Vifon  Mì Gà Tìm Chua Cay Hot & Sour Chicken Flavor I...
1424      1156    Vifon  Oriental Style Instant Vermicelli Sour Crab Fl...
1530      1050    Knorr    Japanese Pork Bone Flavour Quick Serve Macaroni
1629       951    Vifon                           Pomidorowa (Mild Tomato)
1707       873    Vifon                          Viet Rice Noodles Chicken
1734       846    Vifon                                        Mi Kim Chee
1749       831    Vifon                           Instant Porridge Chicken
1864       716    Vifon                             Hu Tieu Ca Stewed Fish
1960       620    Vifon   Phu Gia Bamboo Shoot Artificial Pork Bean Thread
1991       589    Vifon                        South Korean Style Kim Chee
1992       588    Vifon                                        Tu Quy Pork
1997       583    Vifon                       Phu Gia Cua Crab Bean Thread
2017       563  Yum Yum                                               Duck
2026       554  Yum Yum                              Shrimp Tom Yum Flavor
2034       546  Yum Yum                                          Vegetable
2039       541  Yum Yum                                            Chicken
2049       531  Yum Yum                                               Beef
2076       504    Knorr                                              Pizza
2113       467    Vifon                           Tu Quy Sour Spicy Shrimp
2154       426    Vifon                                     Tu quy Chicken
2158       422    Vifon                              Mi Lau Thai Thai Stle
2163       417    Vifon                                  Tu Quy Spicy Beef
2174       406    Vifon                   Asian Style Instant Noodles Beef
2205       375    Vifon                            Pho Bo Beef Rice Noodle
2206       374    Vifon                 Asian Style Instant Noodles Shrimp
2212       368    Knorr                                         Chili Pork
2250       330    Vifon                Phu Gia Instant Bean Thread Chicken
2269       311    Vifon                                     Tasty Mushroom
2352       228    Vifon                         Pho Ga Instant rice Noodle
2403       177    Vifon                        Hu Tieu Bo Kho An Lien Beef
2417       163    Vifon                Asian Style Instant Noodles Chicken
2453       127    Vifon                                 Mi Chay Vegetarian
2574         6    Vifon                                           Nam Vang
2575         5    Vifon  Hu Tiu Nam Vang ["Phnom Penh" style] Asian Sty...

     Style    Country
226   Bowl    Vietnam
234   Pack   Pakistan
387   Pack   Pakistan
674   Pack    Vietnam
713   Bowl   Thailand
748   Pack   Thailand
761   Bowl   Thailand
764   Bowl    Vietnam
831   Pack   Thailand
865   Pack   Thailand
914    Cup    Vietnam
1058  Pack    Vietnam
1060  Pack   Thailand
1070  Pack  Hong Kong
1143  Pack  Hong Kong
1161   Cup    Vietnam
1251   Cup    Vietnam
1271   Cup   Thailand
1279  Pack  Hong Kong
1303  Pack    Vietnam
1424  Pack    Vietnam
1530  Pack  Hong Kong
1629  Pack     Poland
1707  Pack    Vietnam
1734  Pack    Vietnam
1749  Pack    Vietnam
1864  Bowl    Vietnam
1960  Pack    Vietnam
1991  Bowl    Vietnam
1992  Pack    Vietnam
1997  Pack    Vietnam
2017  Pack   Thailand
2026  Pack   Thailand
2034  Pack   Thailand
2039  Pack   Thailand
2049  Pack   Thailand
2076  Pack   Pakistan
2113  Pack    Vietnam
2154  Pack    Vietnam
2158  Bowl    Vietnam
2163  Pack    Vietnam
2174  Pack    Vietnam
2205  Pack    Vietnam
2206  Pack    Vietnam
2212   Cup   Thailand
2250  Pack    Vietnam
2269  Pack    Vietnam
2352  Bowl    Vietnam
2403  Pack    Vietnam
2417  Pack    Vietnam
2453  Pack    Vietnam
2574  Pack    Vietnam
2575  Bowl    Vietnam
--------------------------------------------------

# Task: Grouping And Sorting (Fabian Oppermann)

Use grouping to solve the following tasks:

* Print out the number of reviews per brand in ascending order.
* Print out all the styles and their mean rating points - in descending order.
* Print out the minimum, maximum and mean price per brand, sorted by the maximum values.
* Print out all the values of the highest rated ramen per style!
* Print out the count and mean of ratings per style per brand, sorted by the count.

In [25]:
# Print out the number of reviews per brand in ascending order
print(ramen_df['Brand'].value_counts().sort_values())
print('-' * 50)

# Print out all the styles and their mean rating points - in descending order
print(ramen_df.groupby('Style')['Points'].mean().sort_values(ascending=False))
print('-' * 50)

# Print out the minimum, maximum and mean price per brand, sorted by the maximum values
print(ramen_df.groupby('Brand')['Price'].agg(['min', 'max', 'mean']).sort_values(by='max', ascending=False))
print('-' * 50)

# Print out all the values of the highest rated ramen per style
print(ramen_df.loc[ramen_df.groupby('Style')['Points'].max()])
print('-' * 50)

# Print out the count and mean of ratings per style per brand, sorted by the count
print(ramen_df.groupby(['Brand', 'Style'])['Points'].agg(['count', 'mean']).sort_values(by='count', ascending=False))
print('-' * 50)

Brand
Westbrae              1
Dongwon               1
S&S                   1
Yum-Mie               1
Jackpot Teriyaki      1
                   ...
Paldo                66
Mama                 71
Maruchan             76
Nongshim             98
Nissin              381
Name: count, Length: 355, dtype: int64
--------------------------------------------------
Style
Bar     50.000000
Box     42.916667
Pack    37.004581
Bowl    36.706861
Tray    35.451389
Can     35.000000
Cup     34.985000
Name: Points, dtype: float64
--------------------------------------------------
               min   max      mean
Brand
Vina Acecook  0.79  2.19  0.963529
Bon Go Jang   1.79  2.19  1.990000
Thai Kitchen  0.79  2.19  1.370000
Doll          0.79  2.19  0.940000
Daikoku       1.29  2.19  1.690000
...            ...   ...       ...
Weh Lih       0.79  0.79  0.790000
Wei Chuan     0.79  0.79  0.790000
Zow Zow       0.79  0.79  0.790000
iMee          0.79  0.79  0.790000
iNoodle       0.79  0.79  0.790000

[355 rows x 3 columns]
--------------------------------------------------
    Review #   Brand                                   Variety Style  \
50      2530  Ottogi  Ppushu Ppushu Noodle Snack Honey Butter   Pack
50      2530  Ottogi  Ppushu Ppushu Noodle Snack Honey Butter   Pack
50      2530  Ottogi  Ppushu Ppushu Noodle Snack Honey Butter   Pack
35      2545    KOKA   Instant Noodles Laksa Singapura Flavour  Pack
50      2530  Ottogi  Ppushu Ppushu Noodle Snack Honey Butter   Pack
50      2530  Ottogi  Ppushu Ppushu Noodle Snack Honey Butter   Pack
50      2530  Ottogi  Ppushu Ppushu Noodle Snack Honey Butter   Pack

        Country  Points Top Ten  Price   Textual_Recom
50  South Korea    20.0     NaN   0.79  Budget choice!
50  South Korea    20.0     NaN   0.79  Budget choice!
50  South Korea    20.0     NaN   0.79  Budget choice!
35    Singapore    50.0     NaN   0.79  Budget choice!
50  South Korea    20.0     NaN   0.79  Budget choice!
50  South Korea    20.0     NaN   0.79  Budget choice!
50  South Korea    20.0     NaN   0.79  Budget choice!
--------------------------------------------------
                      count       mean
Brand          Style
Nissin         Cup      165  38.301515
               Pack     121  39.524793
               Bowl      71  40.985915
Mama           Pack      48  35.552083
Indomie        Pack      47  40.957447
...                     ...        ...
Vina Acecook   Cup        1  25.000000
Yum Yum        Cup        1  37.500000
Yum-Mie        Pack       1  35.000000
Zow Zow        Pack       1  37.500000
1 To 3 Noodles Pack       1  40.000000

[489 rows x 2 columns]
--------------------------------------------------

# Good Job!